// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/vadiminshakov/marti/internal/domain"
)

// decisionStoreWriter is an autogenerated mock type for the decisionStoreWriter type
type decisionStoreWriter struct {
	mock.Mock
}

// SaveAI provides a mock function with given fields: event
func (_m *decisionStoreWriter) SaveAI(event domain.AIDecisionEvent) error {
	ret := _m.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for SaveAI")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.AIDecisionEvent) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveAveraging provides a mock function with given fields: event
func (_m *decisionStoreWriter) SaveAveraging(event domain.AveragingDecisionEvent) error {
	ret := _m.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for SaveAveraging")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.AveragingDecisionEvent) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newDecisionStoreWriter creates a new instance of decisionStoreWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newDecisionStoreWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *decisionStoreWriter {
	mock := &decisionStoreWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
