run:
  # Timeout for analysis, e.g. 30s, 5m. Default is 1m.
  deadline: 5m
  # Exit code when at least one issue was found, default is 1
  issues-exit-code: 1
  # Include test files or not, default is true
  tests: true

  # Exclude Go standard library
  build-constraints:
    - !darwin
    - !windows
    - !plan9
    - !js
    - !wasm

# This section provides the configuration for the linters.
linters:
  # Explicitly enable linters
  enable:
    # Code style and formatting
    - gofmt
    - goimports
    - gci
    - gocritic
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - revive
    - errcheck
    - goconst
    - gocyclo
    - goprintffuncname
    - misspell
    - prealloc
    - wrapcheck
    - wsl
    - nlreturn         # Enforces new line before return statements
    - godot            # Enforces correct formatting of comments
    - gofumpt          # More strict gofmt
    - gosec
    
  # Disable specific linters that might be too strict or conflict with others
  disable:
    - gochecknoinits
    - err113
    - godox
    - testpackage

# Linter specific configurations
linters-settings:
  # Configuration for the goimports linter
  goimports:
    # Put imports beginning with prefix after 3rd-party packages.
    local-prefixes: github.com/vadiminshakov/marti
    
  # Configuration for gci (Go Control Import)
  gci:
    # Require specific import order
    sections:
      - standard       # Standard library
      - default         # External packages
      - prefix(github.com/vadiminshakov/marti)  # Local packages
      - blank           # Blank line between sections
      - dot             # Dot imports (should be avoided)
    
  # Enable additional checks for import paths
  staticcheck:
    checks:
      - all
      - -ST1000  # Check for malformed package comments
      - -ST1003  # Check for malformed variable names
      - -ST1005  # Check for malformed error messages
      - -ST1006  # Check for malformed receiver names
      - -ST1008  # Check for malformed error returns
      - -ST1012  # Check for malformed error variables
      - -ST1016  # Check for malformed receiver names
      - -ST1017  # Check for malformed receiver names
      - -ST1018  # Check for malformed receiver names
      - -ST1019  # Check for malformed receiver names
      - -ST1020  # Check for malformed receiver names
      - -ST1021  # Check for malformed receiver names
      - -ST1022  # Check for malformed receiver names
      - -ST1023  # Check for malformed receiver names
      - -ST1024  # Check for malformed receiver names
    
  # Configuration for the revive linter (replacement for golint and nosnakecase)
  revive:
    # The default configuration comes from https://github.com/mgechev/revive/blob/master/config/defaults.toml
    rules:
      - name: var-naming
        disabled: false
        severity: warning
      - name: package-comments
        disabled: false
      - name: exported
        disabled: false
      - name: var-declaration
        disabled: false
      - name: package-comments
        disabled: false
      - name: range
        disabled: false
      - name: receiver-naming
        disabled: false
      - name: time-naming
        disabled: false
      - name: modifies-value-receiver
        disabled: false
      - name: constant-logical-expr
        disabled: false
      - name: modifies-parameter
        disabled: false
      - name: unused-parameter
        disabled: false
      - name: unreachable-code
        disabled: false
      - name: redefines-builtin-id
        disabled: false
    ignore-generated-header: "" # or a regexp for generated files
    severity: warning
    confidence: 0.8
    errorCode: 1
    warningCode: 1
    
  # Configuration for the unused linter (replacement for deadcode, varcheck, structcheck)
  unused:
    check-exported: false  # Set to true to check exported functions and methods
    
  # Configuration for govet (includes fieldalignment check)
  govet:
    settings:
      printf:
        funcs: ["Error", "Errorf", "Info", "Infof", "Warn", "Warnf", "Warning", "Warningf", "Fatal", "Fatalf"]
    enable-all: false
    enable:
      - fieldalignment  # Reports structs that would use less memory if their fields were sorted
      - shadow

  # Configuration for the gocritic linter
  gocritic:
    # Enable multiple checks by tags.
    # Run `GL_DEBUG=gocritic golangci-lint run` to see all tags and checks.
    # Empty list enables all checks.
    enabled-tags:
      - performance
      - style
      - experimental
    # Disabled checks.
    disabled-checks:
      - hugeParam
      - rangeValCopy
      - importShadow

# This section provides the configuration for how golangci runs.
issues:
  # Exclude directories
  exclude-dirs:
    - vendor
    - .git
    - .github
    - .idea
    - .vscode
    - .gitlab
    - docs
    - testdata
    - internal/mock
    - mocks
    - scripts
    - bin
    - tmp
    - _*
  # List of regexps of issue texts to exclude, empty list by default.
  # But independently from this option we use default exclude patterns,
  # it can be disabled by `exclude-use-default: false`.
  # Ex: ".*test.*"
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gosec
        - dupl
        - goconst

    # Exclude common method required for test helpers
    - path: _test\.go$
      text: 'unused method: .*'
