- pair: BTC_USDT
  usebalance: 38
  minwindow: 65
  stathours: 120

- pair: ETH_USDT
  usebalance: 27
  minwindow: 7
  stathours: 240

- pair: BNB_USDT
  usebalance: 20
  minwindow: 0.9
  stathours: 260