// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/vadiminshakov/marti/internal/domain"
)

// balanceSnapshotReader is an autogenerated mock type for the balanceSnapshotReader type
type balanceSnapshotReader struct {
	mock.Mock
}

// SnapshotsAfter provides a mock function with given fields: index
func (_m *balanceSnapshotReader) SnapshotsAfter(index uint64) ([]domain.BalanceSnapshotRecord, error) {
	ret := _m.Called(index)

	if len(ret) == 0 {
		panic("no return value specified for SnapshotsAfter")
	}

	var r0 []domain.BalanceSnapshotRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) ([]domain.BalanceSnapshotRecord, error)); ok {
		return rf(index)
	}
	if rf, ok := ret.Get(0).(func(uint64) []domain.BalanceSnapshotRecord); ok {
		r0 = rf(index)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BalanceSnapshotRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(index)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newBalanceSnapshotReader creates a new instance of balanceSnapshotReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newBalanceSnapshotReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *balanceSnapshotReader {
	mock := &balanceSnapshotReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
