// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/vadiminshakov/marti/internal/domain"
)

// TradingBotInterface is an autogenerated mock type for the TradingBotInterface type
type TradingBotInterface struct {
	mock.Mock
}

// GetPair provides a mock function with no fields
func (_m *TradingBotInterface) GetPair() domain.Pair {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPair")
	}

	var r0 domain.Pair
	if rf, ok := ret.Get(0).(func() domain.Pair); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(domain.Pair)
	}

	return r0
}

// SellAll provides a mock function with given fields: ctx
func (_m *TradingBotInterface) SellAll(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SellAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTradingBotInterface creates a new instance of TradingBotInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTradingBotInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TradingBotInterface {
	mock := &TradingBotInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
