// Code generated by "stringer -type=PositionSide"; DO NOT EDIT.

package entity

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PositionSideLong-0]
	_ = x[PositionSideShort-1]
}

const _PositionSide_name = "PositionSideLongPositionSideShort"

var _PositionSide_index = [...]uint8{0, 16, 33}

func (i PositionSide) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PositionSide_index)-1 {
		return "PositionSide(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PositionSide_name[_PositionSide_index[idx]:_PositionSide_index[idx+1]]
}
