// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/vadiminshakov/marti/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// klineProvider is an autogenerated mock type for the klineProvider type
type klineProvider struct {
	mock.Mock
}

// GetKlines provides a mock function with given fields: ctx, pair, interval, limit
func (_m *klineProvider) GetKlines(ctx context.Context, pair domain.Pair, interval string, limit int) ([]domain.MarketCandle, error) {
	ret := _m.Called(ctx, pair, interval, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetKlines")
	}

	var r0 []domain.MarketCandle
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Pair, string, int) ([]domain.MarketCandle, error)); ok {
		return rf(ctx, pair, interval, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Pair, string, int) []domain.MarketCandle); ok {
		r0 = rf(ctx, pair, interval, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MarketCandle)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Pair, string, int) error); ok {
		r1 = rf(ctx, pair, interval, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newKlineProvider creates a new instance of klineProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newKlineProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *klineProvider {
	mock := &klineProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
