// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/vadiminshakov/marti/internal/domain"
)

// marketDataCollector is an autogenerated mock type for the marketDataCollector type
type marketDataCollector struct {
	mock.Mock
}

// FetchTimeframeData provides a mock function with given fields: ctx, interval, lookback
func (_m *marketDataCollector) FetchTimeframeData(ctx context.Context, interval string, lookback int) (*domain.Timeframe, error) {
	ret := _m.Called(ctx, interval, lookback)

	if len(ret) == 0 {
		panic("no return value specified for FetchTimeframeData")
	}

	var r0 *domain.Timeframe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (*domain.Timeframe, error)); ok {
		return rf(ctx, interval, lookback)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *domain.Timeframe); ok {
		r0 = rf(ctx, interval, lookback)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Timeframe)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, interval, lookback)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMarketDataCollector creates a new instance of marketDataCollector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMarketDataCollector(t interface {
	mock.TestingT
	Cleanup(func())
}) *marketDataCollector {
	mock := &marketDataCollector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
