// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	decimal "github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"
	domain "github.com/vadiminshakov/marti/internal/domain"
)

// tradersvc is an autogenerated mock type for the tradersvc type
type tradersvc struct {
	mock.Mock
}

// ExecuteAction provides a mock function with given fields: ctx, action, amount, clientOrderID
func (_m *tradersvc) ExecuteAction(ctx context.Context, action domain.Action, amount decimal.Decimal, clientOrderID string) error {
	ret := _m.Called(ctx, action, amount, clientOrderID)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteAction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Action, decimal.Decimal, string) error); ok {
		r0 = rf(ctx, action, amount, clientOrderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBalance provides a mock function with given fields: ctx, currency
func (_m *tradersvc) GetBalance(ctx context.Context, currency string) (decimal.Decimal, error) {
	ret := _m.Called(ctx, currency)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 decimal.Decimal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (decimal.Decimal, error)); ok {
		return rf(ctx, currency)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) decimal.Decimal); ok {
		r0 = rf(ctx, currency)
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, currency)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPosition provides a mock function with given fields: ctx, pair
func (_m *tradersvc) GetPosition(ctx context.Context, pair domain.Pair) (*domain.Position, error) {
	ret := _m.Called(ctx, pair)

	if len(ret) == 0 {
		panic("no return value specified for GetPosition")
	}

	var r0 *domain.Position
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Pair) (*domain.Position, error)); ok {
		return rf(ctx, pair)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Pair) *domain.Position); ok {
		r0 = rf(ctx, pair)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Position)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Pair) error); ok {
		r1 = rf(ctx, pair)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderExecuted provides a mock function with given fields: ctx, clientOrderID
func (_m *tradersvc) OrderExecuted(ctx context.Context, clientOrderID string) (bool, decimal.Decimal, error) {
	ret := _m.Called(ctx, clientOrderID)

	if len(ret) == 0 {
		panic("no return value specified for OrderExecuted")
	}

	var r0 bool
	var r1 decimal.Decimal
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, decimal.Decimal, error)); ok {
		return rf(ctx, clientOrderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, clientOrderID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) decimal.Decimal); ok {
		r1 = rf(ctx, clientOrderID)
	} else {
		r1 = ret.Get(1).(decimal.Decimal)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, clientOrderID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SetPositionStops provides a mock function with given fields: ctx, pair, takeProfit, stopLoss
func (_m *tradersvc) SetPositionStops(ctx context.Context, pair domain.Pair, takeProfit decimal.Decimal, stopLoss decimal.Decimal) error {
	ret := _m.Called(ctx, pair, takeProfit, stopLoss)

	if len(ret) == 0 {
		panic("no return value specified for SetPositionStops")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Pair, decimal.Decimal, decimal.Decimal) error); ok {
		r0 = rf(ctx, pair, takeProfit, stopLoss)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newTradersvc creates a new instance of tradersvc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newTradersvc(t interface {
	mock.TestingT
	Cleanup(func())
}) *tradersvc {
	mock := &tradersvc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
