// Code generated by mockery v2.53.5. DO NOT EDIT.

package decisionrecorder

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/vadiminshakov/marti/internal/domain"
)

// DecisionRecorder is an autogenerated mock type for the decisionRecorder type
type DecisionRecorder struct {
	mock.Mock
}

// SaveDCA provides a mock function with given fields: event
func (_m *DecisionRecorder) SaveDCA(event domain.DCADecisionEvent) error {
	ret := _m.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for SaveDCA")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.DCADecisionEvent) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDecisionRecorder creates a new instance of DecisionRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDecisionRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *DecisionRecorder {
	mock := &DecisionRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
