// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	decimal "github.com/shopspring/decimal"

	mock "github.com/stretchr/testify/mock"
)

// Kliner is an autogenerated mock type for the Kliner type
type Kliner struct {
	mock.Mock
}

// ClosePrice provides a mock function with no fields
func (_m *Kliner) ClosePrice() decimal.Decimal {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ClosePrice")
	}

	var r0 decimal.Decimal
	if rf, ok := ret.Get(0).(func() decimal.Decimal); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}

	return r0
}

// OpenPrice provides a mock function with no fields
func (_m *Kliner) OpenPrice() decimal.Decimal {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for OpenPrice")
	}

	var r0 decimal.Decimal
	if rf, ok := ret.Get(0).(func() decimal.Decimal); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}

	return r0
}

// NewKliner creates a new instance of Kliner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKliner(t interface {
	mock.TestingT
	Cleanup(func())
}) *Kliner {
	mock := &Kliner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
