// Code generated by mockery v2.53.5. DO NOT EDIT.

package botmock

import (
	decimal "github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"
)

// DcaCostBasisProvider is an autogenerated mock type for the dcaCostBasisProvider type
type DcaCostBasisProvider struct {
	mock.Mock
}

// GetDcaCostBasis provides a mock function with no fields
func (_m *DcaCostBasisProvider) GetDcaCostBasis() (decimal.Decimal, decimal.Decimal) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDcaCostBasis")
	}

	var r0 decimal.Decimal
	var r1 decimal.Decimal
	if rf, ok := ret.Get(0).(func() (decimal.Decimal, decimal.Decimal)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() decimal.Decimal); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}

	if rf, ok := ret.Get(1).(func() decimal.Decimal); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(decimal.Decimal)
	}

	return r0, r1
}

// NewDcaCostBasisProvider creates a new instance of DcaCostBasisProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDcaCostBasisProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *DcaCostBasisProvider {
	mock := &DcaCostBasisProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
