// Code generated by mockery v2.53.5. DO NOT EDIT.

package botmock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/vadiminshakov/marti/internal/domain"
)

// TradingStrategy is an autogenerated mock type for the tradingStrategy type
type TradingStrategy struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *TradingStrategy) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Initialize provides a mock function with given fields: ctx
func (_m *TradingStrategy) Initialize(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Initialize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SellAll provides a mock function with given fields: ctx
func (_m *TradingStrategy) SellAll(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SellAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Trade provides a mock function with given fields: ctx
func (_m *TradingStrategy) Trade(ctx context.Context) (*domain.TradeEvent, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Trade")
	}

	var r0 *domain.TradeEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.TradeEvent, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.TradeEvent); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TradeEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTradingStrategy creates a new instance of TradingStrategy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTradingStrategy(t interface {
	mock.TestingT
	Cleanup(func())
}) *TradingStrategy {
	mock := &TradingStrategy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
