// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	decimal "github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"
	domain "github.com/vadiminshakov/marti/internal/domain"
)

// Pricer is an autogenerated mock type for the Pricer type
type Pricer struct {
	mock.Mock
}

// GetPrice provides a mock function with given fields: ctx, pair
func (_m *Pricer) GetPrice(ctx context.Context, pair domain.Pair) (decimal.Decimal, error) {
	ret := _m.Called(ctx, pair)

	if len(ret) == 0 {
		panic("no return value specified for GetPrice")
	}

	var r0 decimal.Decimal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Pair) (decimal.Decimal, error)); ok {
		return rf(ctx, pair)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Pair) decimal.Decimal); ok {
		r0 = rf(ctx, pair)
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Pair) error); ok {
		r1 = rf(ctx, pair)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPricer creates a new instance of Pricer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPricer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Pricer {
	mock := &Pricer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
